"""add caterer ops agent tables

Revision ID: 3efa680a4303
Revises: 4b718562af5d
Create Date: 2026-08-06 17:48:49.649173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efa680a4303'
down_revision: Union[str, Sequence[str], None] = '4b718562af5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('completed', 'incomplete', 'error', name='agentrunstatus'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tools_consulted', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_id'), 'agent_runs', ['id'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_date'), 'agent_runs', ['run_date'], unique=False)
    op.create_table('agent_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('drafted_message', sa.Text(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_date', sa.Date(), nullable=True),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'edited', 'rejected', name='actionapprovalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_actions_id'), 'agent_actions', ['id'], unique=False)
    op.create_index(op.f('ix_agent_actions_run_id'), 'agent_actions', ['run_id'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('round_num >= 1', name='ck_agent_traces_round_positive'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_id'), 'agent_traces', ['id'], unique=False)
    op.create_index(op.f('ix_agent_traces_run_id'), 'agent_traces', ['run_id'], unique=False)
    # NOTE: autogenerate also proposed dropping 'idx_one_pending_new' on
    # subscription_requests here — that's unrelated to this migration.
    # It's leftover drift from 4b718562af5d ("drop overly strict unique
    # constraint on subscription_requests"), whose upgrade()/downgrade()
    # were both left as `pass` — the constraint was never actually dropped
    # even though the model stopped declaring it. Left out of this
    # migration deliberately; that's a separate fix for you to make
    # intentionally, not something to bundle in here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_traces_run_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_agent_actions_run_id'), table_name='agent_actions')
    op.drop_index(op.f('ix_agent_actions_id'), table_name='agent_actions')
    op.drop_table('agent_actions')
    op.drop_index(op.f('ix_agent_runs_run_date'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
    # autogenerate does NOT emit these — drop_table alone leaves the native
    # Postgres ENUM types behind (confirmed: re-running upgrade after a
    # downgrade fails with "type already exists" without this).
    sa.Enum(name='actionapprovalstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='agentrunstatus').drop(op.get_bind(), checkfirst=True)