"""add date range to subscription requests

Revision ID: 52108d57e377
Revises: 618ebf57e0df
Create Date: 2026-07-21 11:29:53.268965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52108d57e377'
down_revision: Union[str, Sequence[str], None] = '618ebf57e0df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_requests', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('subscription_requests', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_requests', 'end_date')
    op.drop_column('subscription_requests', 'start_date')
    # ### end Alembic commands ###
