"""add price_plans table

Revision ID: 618ebf57e0df
Revises: df39180936f0
Create Date: 2026-07-03 17:41:04.156787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618ebf57e0df'
down_revision: Union[str, Sequence[str], None] = 'df39180936f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=False),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_type')
    )
    op.create_index(op.f('ix_price_plans_id'), 'price_plans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_plans_id'), table_name='price_plans')
    op.drop_table('price_plans')
    # ### end Alembic commands ###
